
Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-18.04"

   config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "3096"
   end

   config.vm.synced_folder "../../backend_project", "/backend_project"

    config.vm.define :masina_1 do |masina_1|
        masina_1.vm.network :private_network, ip: "10.0.0.10"
        masina_1.vm.hostname = "masina1"
        masina_1.vm.synced_folder "../data_1", "/vagrant_data"
    end

    config.vm.define :masina_2 do |masina_2|
        masina_2.vm.network :private_network, ip: "10.0.0.11"
        masina_2.vm.hostname = "masina2"
        masina_2.vm.synced_folder "../data_2", "/vagrant_data"
    end

     config.vm.define :masina_3 do |masina_3|
        masina_3.vm.network :private_network, ip: "10.0.0.12"
        masina_3.vm.hostname = "masina3"
        masina_3.vm.synced_folder "../data_3", "/vagrant_data"
     end

   config.vm.provision "update", type: "shell",  inline: <<-SHELL
     apt-get update
   SHELL

   config.vm.provision "docker" , after: "update" do |d|
   end

   config.vm.provision "docker_login", type: "shell", after: "docker", inline: <<-SHELL
      docker login --username=icosmin94 -p gigel007
   SHELL
   
  
end
